"""Shared Solution building utilities.

Used by agent_service.py and integration test scripts.
"""

import hashlib

from flashinfer_bench.data import BuildSpec, Solution, SourceFile


def build_solution(
    code: str,
    definition_name: str,
    language: str = "triton",
    binding: str | None = None,
) -> Solution:
    """Build a Solution object from extracted code.

    Supports language modes:
    - python: pure Python solution (e.g. using flashinfer), single main.py
    - triton: Triton kernel with @triton.jit, single main.py
    - cuda/cpp: CUDA kernel with torch C++ extension binding, single main.cpp
    - cuda with binding="tvm-ffi": CUDA kernel with TVM-FFI binding, single kernel.cu
    """
    if language in ("triton", "python"):
        sources = [SourceFile(path="main.py", content=code)]
        entry_point = "main.py::run"
        spec = BuildSpec(
            language=language,
            target_hardware=["cuda"],
            entry_point=entry_point,
            destination_passing_style=False,
        )
    elif language in ("cuda", "cpp") and binding == "tvm-ffi":
        sources = [SourceFile(path="kernel.cu", content=code)]
        entry_point = "kernel.cu::run"
        spec = BuildSpec(
            language="cuda",
            target_hardware=["cuda"],
            entry_point=entry_point,
            binding="tvm-ffi",
            destination_passing_style=True,
        )
    elif language in ("cuda", "cpp"):
        sources = [SourceFile(path="main.cpp", content=code)]
        entry_point = "main.cpp::run"
        spec = BuildSpec(
            language="cuda",
            target_hardware=["cuda"],
            entry_point=entry_point,
            binding="torch",
            destination_passing_style=False,
        )
    else:
        raise ValueError(f"Unsupported language: {language}")

    code_hash = hashlib.sha256(code.encode()).hexdigest()[:8]
    solution_name = f"accrl_{definition_name}_{code_hash}"

    return Solution(
        name=solution_name,
        definition=definition_name,
        author="AccRL",
        spec=spec,
        sources=sources,
        description="Generated by AccRL agent",
    )
